package com.smartcampus.ui;
import com.smartcampus.model.*; import com.smartcampus.enums.*; import com.smartcampus.service.*; import com.smartcampus.exception.*; import com.smartcampus.util.InputValidator; import java.time.LocalDate; import java.util.*;
public class MainMenu {
    private final StudentService students; private final EventService events; private final RegistrationService registrations; private final CertificateService certificates; private final AnalyticsService analytics; private final Scanner sc=new Scanner(System.in);
    public MainMenu(StudentService s,EventService e,RegistrationService r,CertificateService c,AnalyticsService a){students=s;events=e;registrations=r;certificates=c;analytics=a;}
    private String ask(String p){System.out.print(p);return sc.nextLine().trim();}
    public void start(){
        while(true){System.out.println("\n========================================\n SMART CAMPUS EVENT MANAGEMENT\n========================================\n1. Students\n2. Events\n3. Registration & Attendance\n4. Certificates\n5. Reports\n6. Exit");
            String c=ask("Choice: "); try{switch(c){case "1"->studentMenu();case "2"->eventMenu();case "3"->registrationMenu();case "4"->certificateMenu();case "5"->System.out.println(analytics.generateReport());case "6"->{System.out.println("Goodbye.");return;}default->System.out.println("Invalid choice.");}}catch(RuntimeException ex){System.out.println("ERROR: "+ex.getMessage());}}
    }
    private void studentMenu(){while(true){System.out.println("\n-- STUDENTS --\n1 Add\n2 List\n3 Search\n4 Update\n5 Delete\n6 Back");String c=ask("Choice: ");try{switch(c){case"1"->System.out.println("Created: "+students.add(ask("Name: "),ask("Email: "),ask("Program: ")));case"2"->students.all().forEach(System.out::println);case"3"->students.search(ask("Keyword: ")).forEach(System.out::println);case"4"->students.update(ask("ID: "),ask("Name: "),ask("Email: "),ask("Program: "));case"5"->students.delete(ask("ID: "));case"6"-> {return;}default->System.out.println("Invalid choice.");}}catch(RuntimeException ex){System.out.println("ERROR: "+ex.getMessage());}}}
    private void eventMenu(){while(true){System.out.println("\n-- EVENTS --\n1 Create\n2 List\n3 Search\n4 Update\n5 Delete\n6 Back");String c=ask("Choice: ");try{switch(c){case"1"->System.out.println("Created: "+events.create(ask("Name: "),EventType.valueOf(ask("Type (TECHNICAL/CULTURAL/SPORTS/WORKSHOP/SEMINAR): ").toUpperCase()),InputValidator.date(ask("Date YYYY-MM-DD: ")),InputValidator.positiveInt(ask("Capacity: "),"Capacity")));case"2"->events.all().forEach(System.out::println);case"3"->events.search(ask("Keyword: ")).forEach(System.out::println);case"4"->events.update(ask("ID: "),ask("Name: "),EventType.valueOf(ask("Type: ").toUpperCase()),InputValidator.date(ask("Date: ")),InputValidator.positiveInt(ask("Capacity: "),"Capacity"));case"5"->events.delete(ask("ID: "));case"6"->{return;}default->System.out.println("Invalid choice.");}}catch(RuntimeException ex){System.out.println("ERROR: "+ex.getMessage());}}}
    private void registrationMenu(){while(true){System.out.println("\n-- REGISTRATION --\n1 Register\n2 Cancel\n3 Mark Attendance\n4 List\n5 Back");String c=ask("Choice: ");try{switch(c){case"1"->System.out.println("Created: "+registrations.register(ask("Student ID: "),ask("Event ID: ")));case"2"->registrations.cancel(ask("Registration ID: "));case"3"->registrations.attendance(ask("Registration ID: "),AttendanceStatus.valueOf(ask("Attendance (PRESENT/ABSENT/PENDING): ").toUpperCase()));case"4"->registrations.all().forEach(System.out::println);case"5"->{return;}default->System.out.println("Invalid choice.");}}catch(RuntimeException ex){System.out.println("ERROR: "+ex.getMessage());}}}
    private void certificateMenu(){while(true){System.out.println("\n-- CERTIFICATES --\n1 Generate\n2 List\n3 Back");String c=ask("Choice: ");try{switch(c){case"1"->System.out.println("Generated: "+certificates.generate(ask("Registration ID: ")));case"2"->certificates.all().forEach(System.out::println);case"3"->{return;}default->System.out.println("Invalid choice.");}}catch(RuntimeException ex){System.out.println("ERROR: "+ex.getMessage());}}}
}
